<?php

namespace App\Controller\Admin;

use App\Entity\Group;
use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Config\KeyValueStore;
use EasyCorp\Bundle\EasyAdminBundle\Config\Option\EA;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\HttpFoundation\Response;

class GroupController extends AbstractAdminController
{
    public static function getEntityFqcn(): string
    {
        return Group::class;
    }

    final public function getConfigurableFields(string $pageName): array
    {
        $fields = parent::getConfigurableFields($pageName);

        $fields[] = TextField::new('title')
            ->hideOnDetail();

        if (Crud::PAGE_DETAIL !== $pageName) {
            $membersField = AssociationField::new('members')
                ->setCrudController(UserController::class)
                ->autocomplete();
        } else {
            $membersField = CollectionField::new('members');

            $membersField->formatValue(function ($value) {
                $links = array_map(function (User $user) {
                    $url = $this->adminUrlGenerator
                        ->setController(UserController::class)
                        ->setAction(Action::DETAIL)
                        ->setEntityId($user->getId())
                        ->unset(EA::FILTERS)
                        ->unset(EA::PAGE)
                        ->unset(EA::QUERY)
                        ->unset(EA::SORT)
                        ->generateUrl();

                    return sprintf('<a href="%s">%s</a>', $url, $user->getUserIdentifier());
                }, $value->toArray());

                return implode(', ', $links);
            });
        }
        $fields[] = $membersField;

        $statusField = BooleanField::new('status');
        if (Crud::PAGE_INDEX === $pageName) {
            $statusField->renderAsSwitch(false);
        }

        $fields[] = $statusField;

        return $fields;
    }

    final public function configureFilters(Filters $filters): Filters
    {
        $filters = parent::configureFilters($filters);

        return $filters
            ->add('title')
            ->add('status');
    }

    final public function configureCrud(Crud $crud): Crud
    {
        $crud->setPageTitle(Crud::PAGE_EDIT, function ($entityInstance) {
            return sprintf('Edit "%s"', $entityInstance->getTitle());
        });

        $crud->setPageTitle(Crud::PAGE_DETAIL, function ($entityInstance) {
            return $entityInstance->getTitle();
        });

        return parent::configureCrud($crud); // TODO: Change the autogenerated stub
    }

    final public function configureActions(Actions $actions): Actions
    {
        $showGroupAvailability = Action::new('showGroupAvailability', 'Show availability', 'fa fa-regular fa-calendar-check')
            ->linkToCrudAction('groupAvailabilityDetail');

        $actions->add(Crud::PAGE_INDEX, $showGroupAvailability);
        $actions->add(Crud::PAGE_DETAIL, $showGroupAvailability);
        $actions->add(Crud::PAGE_EDIT, $showGroupAvailability);

        return parent::configureActions($actions);
    }

    final public function groupAvailabilityDetail(AdminContext $context): KeyValueStore|Response
    {
        return new Response('nice');
    }
}
